plugins {
    id 'com.android.application' version '9.0.0' apply false
    id 'com.android.library' version '9.0.0' apply false
    id 'org.jetbrains.kotlin.android' version '2.2.0' apply false
    id 'org.jetbrains.kotlin.jvm' version '2.2.0' apply false
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.0' apply false
}

ext {
    room_version = '2.7.1'
    coroutines_version = '1.10.2'
    gson_version = '2.13.1'
    retrofit_version = '2.11.0'
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
