org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true

android.suppressUnsupportedCompileSdk=35

android.useAndroidX=true
android.enableJetifier=true

org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

org.gradle.caching=true

org.gradle.parallel=true

org.gradle.configureondemand=true

kotlin.daemon.jvmargs=-Xmx3072m -Dkotlin.daemon.data.dir=/Volumes/FanXiangMac/DevTools/Gradle/kotlin-daemon

kapt.incremental.apt=true
kapt.use.worker.api=true

kapt.include.compile.classpath=false

android.sdk.channel=3

kotlin.jvm.target.validation.mode=warning

kotlin.incremental=true
kotlin.code.style=official
kotlin.incremental.java=true
kotlin.incremental.js=true

android.nonTransitiveRClass=true
android.nonFinalResIds=true

android.enableComposeCompilerMetrics=true
android.enableComposeCompilerReports=true

org.gradle.daemon=true
